Repository jinx-vi-0/DDoL, pull requests merged in 2024-10, with the labels that each got.

#10 Add Streak Command to LeetCode Discord Bot
  bot.js
Labels: hacktoberfest-accepted, gssoc-ext, Level-2

#17 Dynamic Random Question Fetching
  bot.js
  package-lock.json
  package.json
Labels: enhancement, hacktoberfest-accepted, gssoc-ext, Level-3

#21 Enhanced UI Message for potd & random cmd
  bot.js
Labels: enhancement, hacktoberfest-accepted, gssoc-ext, Level-2

#20 Feature/command handling
  .vscode/launch.json
  bot.js
  commands/Leetcode/potd.mjs
  commands/Leetcode/random.mjs
  commands/Leetcode/user.mjs
  commands/Util/help.mjs
  commands/Util/streak.mjs
  handler.js
  package-lock.json
  problems.js
Labels: enhancement, hacktoberfest-accepted, gssoc-ext, Level-3

#26 #Add greetings.yml
  .github/workflows/greetings.yml
Labels: hacktoberfest-accepted, gssoc-ext, level1

#32 update Readme
  README.md
Labels: documentation, good first issue, hacktoberfest-accepted, gssoc-ext, level1

#34 Add corrected current streak for streak command
  bot.js
Labels: hacktoberfest-accepted, gssoc-ext, level2

#40 Migrated from Message Commands to Slash Commands
  bot.js
  cache/problems.json
  events/interactionCreate.js
  events/messageCreate.js
  events/ready.js
  example.env
  interactions/buttons/topic.js
  interactions/commands/help.js
  interactions/commands/potd.js
  interactions/commands/random.js
  interactions/commands/streak.js
  interactions/commands/topics.js
  interactions/commands/user.js
  utility/KeepAlive.js
  utility/LeetCode.js
Labels: enhancement, hacktoberfest-accepted, gssoc-ext, level3

#44 Updated readme to include slash commands related changes
  README.md
Labels: good first issue, hacktoberfest-accepted, gssoc-ext, level1

#45 Improved Help Command
  interactions/commands/help.js
Labels: enhancement, hacktoberfest-accepted, gssoc-ext, level2

#50 Improved daily LeetCode question feature
  events/ready.js
Labels: hacktoberfest-accepted, gssoc-ext, level2

#51 Added Difficulty in Topics Command
  interactions/buttons/topic.js
  interactions/commands/topics.js
Labels: hacktoberfest-accepted, gssoc-ext

#56 Implemented Contest Reminder 1 hr before
  .vscode/c_cpp_properties.json
  .vscode/launch.json
  .vscode/settings.json
  events/ready.js
Labels: enhancement, hacktoberfest-accepted, gssoc-ext, level2

#61 added contests command to see upcoming leetcode contests
  interactions/commands/contests.js
Labels: hacktoberfest-accepted, gssoc-ext, level2
